# =-------------------------= GERAL =---------------------------= #

MySQL:
  Address: ""
  Port: 3306
  Username: ""
  Password: ""
  Database: ""

# Fuso horário das datas
# "GMT-3" - Horário de Brasília
FusoHorario: "GMT-3"

# =-------------------------= LOGS =---------------------------= #

Logs:
  # Salvar logs de Entrada
  Entrada: true
  # Salvar logs de Saída
  Saida: true
  # Salvar logs de Mensagem
  Mensagem: true
  # Salvar logs de Comandos
  Comando: true

# =-----------------------= COMANDO =-------------------------= #

# O comando por default é /moonlogs e /logs.
Comando:
  Permission: "moonlogs.use"
  Permission-Message: "&cVocê não tem permissão para usar esse comando."
  Usage: "&cUso /moonlogs <jogador>"